# Generated by Django 3.2.7 on 2021-09-17 13:01

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ("extras", "0062_clear_secrets_changelog"),
        ("tenancy", "0001_squashed_0012"),
        ("netbox_dns", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="zone",
            name="expire_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="zone",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="zones",
                to="tenancy.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="zone",
            name="tags",
            field=taggit.managers.TaggableManager(
                through="extras.TaggedItem", to="extras.Tag"
            ),
        ),
    ]
