# Generated by Django 4.0.4 on 2022-04-25 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_dns", "0012_consolidate_model"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="zone",
            options={"ordering": ("view", "name")},
        ),
        migrations.RemoveConstraint(
            model_name="record",
            name="unique_pointer_for_address",
        ),
    ]
