# Generated by Django 4.0.8 on 2022-10-26 18:55

from django.db import migrations
import netbox_dns.fields.network


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_dns", "0017_alter_record_ttl"),
    ]

    operations = [
        migrations.AddField(
            model_name="zone",
            name="arpa_network",
            field=netbox_dns.fields.network.NetworkField(blank=True, null=True),
        ),
    ]
