# Generated by Django 4.1.4 on 2022-12-15 10:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import netbox_dns.fields.address
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ("extras", "0084_staging"),
        ("netbox_dns", "0020_netbox_3_4"),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="ip_address",
            field=netbox_dns.fields.address.AddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="record",
            name="tags",
            field=taggit.managers.TaggableManager(
                through="extras.TaggedItem", to="extras.Tag"
            ),
        ),
        migrations.AlterField(
            model_name="zone",
            name="soa_expire",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name="zone",
            name="soa_minimum",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name="zone",
            name="soa_mname",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="zones_soa",
                to="netbox_dns.nameserver",
            ),
        ),
        migrations.AlterField(
            model_name="zone",
            name="soa_refresh",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name="zone",
            name="soa_retry",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name="zone",
            name="soa_rname",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="zone",
            name="soa_ttl",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
    ]
